apiVersion: apps/v1
kind: Deployment
metadata:
  name: sw-api-deployment
  labels:
    app: sw-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sw-api
  template:
    metadata:
      labels:
        app: sw-api
    spec:
      containers:
        - name: sw-api
          image: sw-api:v1.1
          ports:
            - containerPort: 9090
