apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sw-api-deployment
  namespace: default
spec:
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 40
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sw-api-deployment
